language: perl
sudo: false
perl:
   - "5.8"
   - "5.10"
   - "5.12"
   - "5.14"
   - "5.16"
   - "5.18"
   - "5.20"
   - "5.22"
   - "5.24"
   - "blead"

before_install:
   - git clone git://github.com/haarg/perl-travis-helper
   - source perl-travis-helper/init
   - build-perl
   - perl -V
   - build-dist
   - cd $BUILD_DIR

install:
   - cpan-install --deps

script:
   - make test
